name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12.14.1
      uses: actions/setup-node@v1
      with:
        node-version: "12.14.1"

    - name: npm ci and build
      run: |
        npm ci
        npm run build

    - name: Deploy master to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@2.0.0
      env:
        ACCESS_TOKEN: ${{ secrets.DEV_GITHUB_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dist
